#!/usr/bin/python

import serial
import sys

portname = sys.argv[1]

defaults = dict(bytesize=8, parity=serial.PARITY_NONE, stopbits=1, rtscts=1)

devices = dict(
    msp_top = dict(write='hello', read='MSPTop', settings=dict(baudrate=9600, **defaults)),
    msp_bottom = dict(write='hello', read='MSPBottom', settings=dict(baudrate=9600, **defaults)),
    gps = dict(read='$GP', settings=dict(baudrate=9600, **defaults)),
    transducer = dict(read='$SD', settings=dict(baudrate=4800, **defaults)))

def probeport(name, settings, read, write=None):
    port = serial.Serial(name, timeout=1, **settings)
    port.readlines()
    port.flush()
    if write:
        port.write("\n%s\n" % write)
    recv = port.readline().rstrip('\r\n')
    port.close()
    return recv == read

for device, params in devices.items():
    if probeport(portname, **params):
        print device
        break
