__all__ = ['identity',
           'logger',
           'configuration',
           'registry',
           'dispatcher',
           'rpccomponent',
           'basecomponent',
           'idler',
           'registrycomponent',
           'loggercomponent',
           'mongocomponent',
           'webgate',
]
